In [1]:
#importing the Libraies
import numpy as np
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('50_Startups.csv')

In [5]:
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [7]:
datasets=pd.get_dummies(dataset,drop_first=True)

In [9]:
datasets

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,False,True
1,162597.70,151377.59,443898.53,191792.06,False,False
2,153441.51,101145.55,407934.54,191050.39,True,False
3,144372.41,118671.85,383199.62,182901.99,False,True
4,142107.34,91391.77,366168.42,166187.94,True,False
5,131876.90,99814.71,362861.36,156991.12,False,True
6,134615.46,147198.87,127716.82,156122.51,False,False
7,130298.13,145530.06,323876.68,155752.60,True,False
8,120542.52,148718.95,311613.29,152211.77,False,True
9,123334.88,108679.17,304981.62,149759.96,False,False
10,101913.08,110594.11,229160.95,146121.95,True,False
11,100671.96,91790.61,249744.55,144259.40,False,False
12,93863.75,127320.38,249839.44,141585.52,True,False
13,91992.39,135495.07,252664.93,134307.35,False,False
14,119943.24,156547.42,256512.92,132602.65,True,False
15,114523.61,122616.84,261776.23,129917.04,False,True
16,78013.11,121597.55,264346.06,126992.93,False,False
17,94657.16,145077.58,282574.31,125370.37,False,True
18,91749.16,114175.79,294919.57,124266.90,True,False
19,86419.70,153514.11,0.00,122776.86,False,True
20,76253.86,113867.30,298664.47,118474.03,False,False
21,78389.47,153773.43,299737.29,111313.02,False,True
22,73994.56,122782.75,303319.26,110352.25,True,False
23,67532.53,105751.03,304768.73,108733.99,True,False
24,77044.01,99281.34,140574.81,108552.04,False,True
25,64664.71,139553.16,137962.62,107404.34,False,False
26,75328.87,144135.98,134050.07,105733.54,True,False
27,72107.60,127864.55,353183.81,105008.31,False,True
28,66051.52,182645.56,118148.20,103282.38,True,False
29,65605.48,153032.06,107138.38,101004.64,False,True
30,61994.48,115641.28,91131.24,99937.59,True,False
31,61136.38,152701.92,88218.23,97483.56,False,True
32,63408.86,129219.61,46085.25,97427.84,False,False
33,55493.95,103057.49,214634.81,96778.92,True,False
34,46426.07,157693.92,210797.67,96712.80,False,False
35,46014.02,85047.44,205517.64,96479.51,False,True
36,28663.76,127056.21,201126.82,90708.19,True,False
37,44069.95,51283.14,197029.42,89949.14,False,False
38,20229.59,65947.93,185265.10,81229.06,False,True
39,38558.51,82982.09,174999.30,81005.76,False,False
40,28754.33,118546.05,172795.67,78239.91,False,False
41,27892.92,84710.77,164470.71,77798.83,True,False
42,23640.93,96189.63,148001.11,71498.49,False,False
43,15505.73,127382.30,35534.17,69758.98,False,True
44,22177.74,154806.14,28334.72,65200.33,False,False
45,1000.23,124153.04,1903.93,64926.08,False,True
46,1315.46,115816.21,297114.46,49490.75,True,False
47,0.00,135426.92,0.00,42559.73,False,False
48,542.05,51743.15,0.00,35673.41,False,True
49,0.00,116983.80,45173.06,14681.40,False,False

In [11]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [13]:
indep=datasets[['R&D Spend','Administration', 'Marketing Spend','State_Florida', 'State_New York']]
dep=datasets[['Profit']]

In [15]:

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
param_grid = {
    'n_estimators': [10,100,1000],
    'criterion': ['squared_error', 'absolute_error'],
    'max_features': [None,'sqrt', 'log2'], 
    'bootstrap': [True, False]    
}
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True, verbose=3,n_jobs=-1)
grid.fit(indep,dep)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

C:\Users\alkar\anaconda3\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'bootstrap': [True, False],
                         'criterion': ['squared_error', 'absolute_error'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [10, 100, 1000]},
             verbose=3)

In [19]:
re=grid.cv_results_
print ("the R_score value for best parameter {}:".format(grid.best_params_))

the R_score value for best parameter {'bootstrap': True, 'criterion': 'squared_error', 'max_features': None, 'n_estimators': 10}:

In [ ]:
print(f"the R_score value for best Parameter is: {best_tree}")

In [23]:
table=pd.DataFrame.from_dict(re)

In [25]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_bootstrap,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.028920,0.006920,0.004282,0.000436,True,squared_error,None,10,"{'bootstrap': True, 'criterion': 'squared_erro...",-5.053339,-3.777902,-6.757789,-1.755863,-2.031096,-3.875198,1.876119,1
1,0.167109,0.012495,0.008704,0.000624,True,squared_error,None,100,"{'bootstrap': True, 'criterion': 'squared_erro...",-5.234227,-3.122908,-8.254506,-2.000176,-2.216259,-4.165615,2.342533,4
2,2.587504,0.126124,0.170159,0.009964,True,squared_error,None,1000,"{'bootstrap': True, 'criterion': 'squared_erro...",-5.335480,-3.261329,-7.936746,-1.839708,-2.245810,-4.123815,2.258075,3
3,0.019989,0.001877,0.004462,0.000832,True,squared_error,sqrt,10,"{'bootstrap': True, 'criterion': 'squared_erro...",-7.809300,-6.544784,-15.962028,-0.181282,-3.861413,-6.871762,5.242968,31
4,0.151602,0.002608,0.008146,0.000589,True,squared_error,sqrt,100,"{'bootstrap': True, 'criterion': 'squared_erro...",-7.276229,-6.990031,-9.371879,-1.750635,-3.911219,-5.859998,2.694461,21
5,4.001907,0.509136,0.163899,0.005965,True,squared_error,sqrt,1000,"{'bootstrap': True, 'criterion': 'squared_erro...",-7.511388,-7.240545,-8.290683,-1.360712,-4.042911,-5.689248,2.605411,19
6,0.056670,0.002563,0.009606,0.000823,True,squared_error,log2,10,"{'bootstrap': True, 'criterion': 'squared_erro...",-7.464270,-7.843846,-12.462890,-3.995947,-3.828609,-7.119112,3.155373,33
7,0.476487,0.014039,0.025441,0.002286,True,squared_error,log2,100,"{'bootstrap': True, 'criterion': 'squared_erro...",-7.253126,-6.454295,-9.334207,-1.244824,-3.804461,-5.618183,2.814136,18
8,4.646374,0.040662,0.166678,0.004613,True,squared_error,log2,1000,"{'bootstrap': True, 'criterion': 'squared_erro...",-7.420445,-7.417117,-8.390810,-1.393186,-4.059558,-5.736223,2.622290,20
9,0.064676,0.004272,0.010757,0.001637,True,absolute_error,None,10,"{'bootstrap': True, 'criterion': 'absolute_err...",-6.410319,-4.088425,-9.985231,-3.871664,-2.056399,-5.282407,2.728064,11
10,0.548718,0.012091,0.025508,0.000524,True,absolute_error,None,100,"{'bootstrap': True, 'criterion': 'absolute_err...",-6.006805,-3.713425,-7.699374,-1.689120,-2.100203,-4.241785,2.300080,5
11,5.331925,0.026861,0.162386,0.003488,True,absolute_error,None,1000,"{'bootstrap': True, 'criterion': 'absolute_err...",-5.651114,-3.528479,-6.464072,-1.948737,-2.264272,-3.971335,1.802026,2
12,0.060118,0.001903,0.009677,0.000950,True,absolute_error,sqrt,10,"{'bootstrap': True, 'criterion': 'absolute_err...",-8.567670,-10.745926,-11.953338,-1.710337,-3.911897,-7.377833,3.945332,35
13,0.506914,0.007833,0.025760,0.000991,True,absolute_error,sqrt,100,"{'bootstrap': True, 'criterion': 'absolute_err...",-7.192563,-7.082564,-6.214654,-1.208450,-4.211563,-5.181959,2.256179,10
14,4.977448,0.018440,0.164126,0.006630,True,absolute_error,sqrt,1000,"{'bootstrap': True, 'criterion': 'absolute_err...",-7.559899,-7.158824,-5.495024,-0.887593,-4.120966,-5.044461,2.413850,8
15,0.059935,0.003113,0.010556,0.000956,True,absolute_error,log2,10,"{'bootstrap': True, 'criterion': 'absolute_err...",-7.333595,-4.981761,-11.278670,-3.107376,-4.170338,-6.174348,2.906634,22
16,0.508168,0.005920,0.023427,0.002089,True,absolute_error,log2,100,"{'bootstrap': True, 'criterion': 'absolute_err...",-7.571352,-6.601600,-4.338567,-1.190642,-4.432191,-4.826870,2.204460,6
17,4.958308,0.035813,0.167758,0.003750,True,absolute_error,log2,1000,"{'bootstrap': True, 'criterion': 'absolute_err...",-7.374540,-6.842291,-5.922905,-1.073903,-4.091315,-5.060991,2.284976,9
18,0.043062,0.002093,0.011019,0.000966,False,squared_error,None,10,"{'bootstrap': False, 'criterion': 'squared_err...",-6.477074,-3.058684,-13.428168,-2.006452,-1.671187,-5.328313,4.392900,15
19,0.346320,0.006564,0.025276,0.003779,False,squared_error,None,100,"{'bootstrap': False, 'criterion': 'squared_err...",-6.479743,-3.259497,-13.328633,-2.051109,-1.671351,-5.358067,4.329432,16
20,3.273477,0.035051,0.164135,0.006586,False,squared_error,None,1000,"{'bootstrap': False, 'criterion': 'squared_err...",-6.482227,-3.409100,-13.314798,-2.017372,-1.671411,-5.378982,4.315583,17
21,0.041248,0.002605,0.010543,0.001223,False,squared_error,sqrt,10,"{'bootstrap': False, 'criterion': 'squared_err...",-8.424479,-6.770512,-4.587212,-1.561204,-3.677679,-5.004217,2.391900,7
22,0.326760,0.009867,0.026249,0.001475,False,squared_error,sqrt,100,"{'bootstrap': False, 'criterion': 'squared_err...",-8.074216,-7.692287,-12.079081,-1.764681,-3.739693,-6.669992,3.603440,29
23,3.117294,0.026723,0.173985,0.004119,False,squared_error,sqrt,1000,"{'bootstrap': False, 'criterion': 'squared_err...",-7.894228,-6.806439,-11.290193,-2.168621,-3.850280,-6.401953,3.184887,27
24,0.040740,0.002196,0.011104,0.001047,False,squared_error,log2,10,"{'bootstrap': False, 'criterion': 'squared_err...",-9.381417,-4.084254,-14.894799,-3.348120,-3.733320,-7.088382,4.482610,32
25,0.324880,0.007840,0.025688,0.002417,False,squared_error,log2,100,"{'bootstrap': False, 'criterion': 'squared_err...",-8.434214,-6.817058,-12.159374,-2.447574,-3.875479,-6.746740,3.431504,30
26,3.183515,0.016047,0.174928,0.013678,False,squared_error,log2,1000,"{'bootstrap': False, 'criterion': 'squared_err...",-7.971020,-6.713950,-11.942688,-2.168524,-3.873811,-6.533999,3.390731,28
27,0.053630,0.002385,0.010347,0.001511,False,absolute_error,None,10,"{'bootstrap': False, 'criterion': 'absolute_er...",-4.800427,-2.969266,-13.419025,-2.647581,-2.734977,-5.314255,4.128295,13
28,0.427162,0.006038,0.025287,0.001122,False,absolute_error,None,100,"{'bootstrap': False, 'criterion': 'absolute_er...",-4.810089,-3.009426,-13.394344,-2.513806,-2.744229,-5.294379,4.130371,12
29,4.302340,0.053840,0.164074,0.006154,False,absolute_error,None,1000,"{'bootstrap': False, 'criterion': 'absolute_er...",-4.815760,-3.197350,-13.344389,-2.533102,-2.743062,-5.326732,4.087980,14
30,0.046252,0.002514,0.010327,0.000800,False,absolute_error,sqrt,10,"{'bootstrap': False, 'criterion': 'absolute_er...",-7.575154,-8.017777,-14.096649,-3.183001,-3.598898,-7.294296,3.935302,34
31,0.388348,0.008837,0.022530,0.002207,False,absolute_error,sqrt,100,"{'bootstrap': False, 'criterion': 'absolute_er...",-7.860101,-6.398881,-10.553893,-3.199110,-3.718930,-6.346183,2.713156,26
32,3.635453,0.047739,0.157793,0.011948,False,absolute_error,sqrt,1000,"{'bootstrap': False, 'criterion': 'absolute_er...",-7.756183,-6.546901,-10.393073,-2.653022,-4.120946,-6.294025,2.719677,23
33,0.048849,0.001157,0.010299,0.000373,False,absolute_error,log2,10,"{'bootstrap': False, 'criterion': 'absolute_er...",-8.726372,-7.806168,-18.827703,-4.733012,-4.773172,-8.973285,5.179837,36
34,0.372775,0.006018,0.025533,0.000544,False,absolute_error,log2,100,"{'bootstrap': False, 'criterion': 'absolute_er...",-7.661845,-6.451694,-11.054435,-2.290611,-4.066490,-6.305015,3.018143,24
35,3.428830,0.031673,0.141683,0.011847,False,absolute_error,log2,1000,"{'bootstrap': False, 'criterion': 'absolute_er...",-7.846402,-6.543633,-10.246366,-2.904253,-4.063230,-6.320777,2.628939,25

In [31]:
import pickle
filename="finalized_model_RandomForest_wo_testntrain.sav"
pickle.dump(grid,open(filename,'wb'))

In [33]:
loaded_model=pickle.load(open("finalized_model_RandomForest_wo_testntrain.sav",'rb'))
result=loaded_model.predict([[144372.41,118671.85,383199.62,0,1]])

C:\Users\alkar\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [35]:
result

array([181230.585])